---
sudo: required

services:
  - docker

# set language to anythoing other than Ruby so it doesn't use RVM which winds up overriding the RUBY_VERSION variable
language: c

install: true

before_script:
  - docker info
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" quay.io

script: ./build_and_push
