---
sudo: required

services:
  - docker

# set language to anythoing other than Ruby so it doesn't use RVM which winds up overriding the RUBY_VERSION variable
language: c

env:
  - TEMPLATE=alpine BASE_IMAGE=alpine:3.4
  - TEMPLATE=alpine BASE_IMAGE=alpine:3.5
  - BASE=ubuntu-16.04

install: true

before_script:
  - docker info
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" quay.io

script: ./build_and_push
